language: node_js
  - "8"

branches:
  only:
  - master

before_script:
  - npm install -g ganache-cli
  - npm install -g truffle@5.0.0
  - npm install

script:
  - ganache-cli &
  - sleep 5
  - truffle test
